[package]
name = "caddy-gen"
version = "0.1.0"
edition = "2024"
description = "Generate Caddyfile.dev from a template"
authors = ["Wlad Paiva <me@wladpaiva.xyz>"]
license = "MIT"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
